### ISSUE TITLE
commenting

### ISSUE THREAD

**Issue by aflower15** [Lab41/pythia#52] opened 2016-07-01 17:59 UTC
adding docstring comments to all modules and methods in compliance with the examples shown [here](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html). also research the docutils and sphinx packages for creating docs

**Comment by pcallier** [comment] 2016-08-23 18:30
Duplicate of #22

**Closed by pcallier** 2016-08-23 18:30 UTC
